services:
  - type: web
    name: django-blog-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn blog_api.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: blog_api.settings
      - key: PYTHON_VERSION
        value: 3.12
    plan: free
envVars:
  - key: DJANGO_SETTINGS_MODULE
    value: blog_api.settings
  - key: DEBUG
    value: "False"
  - key: ALLOWED_HOSTS
    value: django-blog-api-8osr.onrender.com
